### ISSUE TITLE
The KML is generated using machine name not public name

### ISSUE THREAD

**Issue by mgg-eagle** [grst/geos#9] opened 2017-05-31 21:45 UTC
Hi there, are you able to add a new command line argument to enter the publicly available name of the server?  The KML that is generated references the machine name, which my desktop client cannot see.  If I manually edit the network links and change the server name then it is all good.

Thanks,
Marc

**Comment by grst** [comment] 2017-06-02 08:27
As of PR #8, there are the (atm undocumented) CLI parameters
```
--display-host geos.example.org
--display-port 443
--display-scheme https
```

The PR is merged, but not uploaded on pip yet. But if you use the version from git this should work.

**Comment by mgg-eagle** [comment] 2017-06-03 00:42
That's cool thanks.  I have installed the latest version from github, but I am getting the following error when I try and run it: 
```
C:\Python3\Scripts>geos
  Restarting with stat
  File "C:\Python3\Scripts\geos.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file C:\Python3\Scripts\geos.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by grst** [comment] 2017-06-03 06:26
That's the windows-problem described in #5 which I cannot reproduce. 
As far as I understand, the problem arises when one tries to execute a binary (`.exe`) as a script (e.g. `python geos.exe`)

Could you please describe step-by-step what you have done?

**Comment by mgg-eagle** [comment] 2017-06-03 06:43
Downloaded the latest version of python 3.6.1 and installed to c:\python3. Downloaded a zip file from github of your code and installed using pip. Tried to run geos as per last comment.

**Comment by grst** [comment] 2017-06-08 07:53
I cannot reproduce that issue, but I now have a suspicion that it has something to do with the Flask debug mode. 

Can you try the following: 
* Download and extract the zip
* edit the file `geos/default_settings.py`: Change `DEBUG = True` to `DEBUG = False`
* go to the root directory of the repository
* install the package with `pip install -e . `

**Comment by mgg-eagle** [comment] 2017-06-09 06:05
That works now thanks.

**Closed as completed** 2017-06-09 08:31 UTC

**Comment by grst** [comment] 2017-06-09 09:33
fyi: The cli-args are now part of the version on pip and included in the documentation.
